POST http://localhost:5001/api/item
Content-Type: application/json

{
    "name": "Notebook",
    "description": "Notebook Dell",
    "value": 3500,
    "location": "L-21",
    "supplier": "Dell",
    "serialNumber": "12KJNI",
    "tag": 123

}

### 
GET http://localhost:5001/api/item/count-value

###

POST http://localhost:5001/api/user
Content-Type: application/json

{
    "name": "Michelle",
    "email": "michelle@email.com",
    "pass": "senha",
    "department": "Vet"
}

### 
GET http://localhost:5001/api/user/648e49f1256722d05fb5a3f0

### 
POST http://localhost:5001/api/movement

{
    "name": "Notebook",
    "actualLocation": "L-21",
    "newLocation": "L-22",
    "reason": "Faltava um computador na sala L-22",
    "observations": "Troca realizada.",
    
}

###
GET http://localhost:5001/api/item/123

###
GET http://localhost:5001/api/movement

### 
POST http://localhost:5001/api/inventory

{
    "location": "L-21",
    "responsable": "Eduardo",
    "inventoriedItems": "Notebook"
}

###
POST http://localhost:5001/client/inventarios/inventory
Content-Type: application/json

 {
      "location": "L-21",
      "responsable": "Admin",
      "item": [
        "Notebook Dell"
      ],
    },